poke327: terrain_generation.cpp world_generation.cpp heap.cpp file_parsing.cpp battle.cpp character_movement.cpp
	g++ -g heap.cpp terrain_generation.cpp battle.cpp character_movement.cpp world_generation.cpp file_parsing.cpp -o poke327 -lncurses
clean:
	rm -f *~ ~o core
