user_interface: terrain_generation.cpp world_generation.cpp heap.cpp file_parsing.cpp
	g++ -g heap.cpp terrain_generation.cpp world_generation.cpp file_parsing.cpp -o user_interface -lncurses
clean:
	rm -f *~ ~o core
